### ISSUE TITLE
unable to install - since laravel 8.14.0

### ISSUE THREAD

**Issue by hsyir** [sanjabteam/baloot#12]
previously i installed the package on laravel 8 but now:
  
Problem 1
    - Root composer.json requires sanjabteam/baloot 1.0.3 -> satisfiable by sanjabteam/baloot[1.0.3].
    - sanjabteam/baloot 1.0.3 requires illuminate/support ^6 | ^7 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.

**Comment by amir9480** [comment]
@hsyir 
سلام
پشیبانی از لاراول 8 اضافه شد
ورژن
1.1.0
پکیج رو استفاده کنین
