### ISSUE TITLE
ثبت تاریخ اشتباه

### ISSUE THREAD

**Issue by hsyir** [sanjabteam/baloot#13]
سلام
خسته نباشید
در هنگام ثبت تاریخ ، تاریخی که در دیتابیس درج میشه یک روز خطا داره
1395/4/5
تبدیل میشه به 
1395/4/4

البته فکر میکنم به ورتا مربوط باشه
لطفا راهنمایی کنید

**Comment by amir9480** [comment]
@hsyir
سلام
احتمالا این خطا به خاطر مشکل عدم توجه به
timezone
برای ورتا باشه

لطفاورتا رو به آخرین ورژن آپلود کنین و اگه حل نشد
خطا رو در
https://github.com/hekmatinasser/verta/
گزارش بدین
