### ISSUE TITLE
مشکل در سید شهرها

### ISSUE THREAD

**Issue by alirezarazavi** [sanjabteam/baloot#17]
سلام. 
موقع سید شهرها پیغام خطای 
` Declaration of Baloot\Models\Province::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array`
دریافت میکنم.
تو فایل دیتابیس سیدر
`\Baloot\Database\CitiesTableSeeder::class,`
اضافه کردم و با 
`migrate:fresh --seed`
انجام میدم

**Comment by mralikeshtkar** [comment]
سلام داخل مدل باید متد که تعریف میشه به این صورت باشه فکر کنم.
sluggable(): array

**Comment by amir9480** [comment]
@alirezarazavi 
سلام
ممنون بابت گزارش
مشکل در نسخه 1.3.0 برطرف شده

**Comment by mralikeshtkar** [comment]
مخصلم 🙌
