### ISSUE TITLE
ساپورت لاراول نسخه ۹

### ISSUE THREAD

**Issue by alirezarazavi** [sanjabteam/baloot#20]
موقع نصب روی لاراول نسخه ۹ خطا میده. 

```
 Problem 1
    - Root composer.json requires sanjabteam/baloot ^1.3 -> satisfiable by sanjabteam/baloot[v1.3.0].
    - sanjabteam/baloot v1.3.0 requires hekmatinasser/verta ^1.10 -> found hekmatinasser/verta[v1.10.0, ..., v1.12.7] but it conflicts with your root composer.json require (^2.1).
```

**Comment by reziamini** [comment]
حل شد

**Comment by javad-90b** [comment]
سلام ، دوباره خطا میده :

Problem 1
    - Root composer.json requires sanjabteam/baloot ^1.3 -> satisfiable by sanjabteam/baloot[v1.3.0].
    - sanjabteam/baloot v1.3.0 requires illuminate/support ^7 | ^8 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require sanjabteam/baloot:*" to figure out if any version is installable, or "composer require sanjabteam/baloot:^2.1" if you know which you need.

**Comment by JBarandeh** [comment]
> حل شد

سلام ، دوباره خطا میده :

Problem 1
    - Root composer.json requires sanjabteam/baloot ^1.3 -> satisfiable by sanjabteam/baloot[v1.3.0].
    - sanjabteam/baloot v1.3.0 requires illuminate/support ^7 | ^8 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require sanjabteam/baloot:*" to figure out if any version is installable, or "composer require sanjabteam/baloot:^2.1" if you know which you need.

**Comment by hsyir** [comment]
+1
